/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.Impl.Exception.DAOException;
import Control.Impl.ImplEventoDAO;
import Control.Impl.ImplFuncionarioDAO;
import Control.Impl.ImplIdosoDAO;
import Model.Evento;
import Model.Funcionario;
import Model.Idoso;
import Util.ComponentValidator;
import Util.Mensagens;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Eduardo
 */
public class FrameCadastroEvento extends javax.swing.JFrame {

    private ArrayList<Idoso> idosos;
    
    private ArrayList<Idoso> idososEdicao;
    
    private Evento evento;
    
    /**
     * Creates new form FrameCadastroEvento
     */
    public FrameCadastroEvento() {
        initComponents();
        
        try {
            List<Idoso> lista = ImplIdosoDAO.getInstance().encontrarTodosIdosos();
            if(lista != null) {
                for (Iterator<Idoso> it = lista.iterator(); it.hasNext();) {
                    Idoso idoso = it.next();
                    comboBoxIdoso.addItem(idoso);
                    comboBoxIdosoEdicao.addItem(idoso);
                }
            }
            
            List<Funcionario> listaFunc = ImplFuncionarioDAO.getInstance().encontraFuncCuidador();
            if(listaFunc != null) {
                for (Iterator<Funcionario> it = listaFunc.iterator(); it.hasNext();) {
                    Funcionario func = it.next();
                    comboFuncionario.addItem(func);
                    comboFuncionarioConsulta.addItem(func);
                }
            }
        } catch(SQLException | DAOException ex) {
            ex.printStackTrace();
        }
        idosos = new ArrayList<>();
        idososEdicao = new ArrayList<>();
    }
    
    private void limparCadastro() {
        campoNome.setText("");
        campoData.setText("");
        comboBoxIdoso.setSelectedIndex(0);
        listIdosos.setModel(new DefaultListModel());
    }
    
    private void limparEdicao() {
        comboBoxEvento.setSelectedIndex(0);
        campoNomeEdicao.setText("");
        campoDataEdicao.setText("");
        comboBoxIdosoEdicao.setSelectedIndex(0);
        listIdososEdicao.setModel(new DefaultListModel());
        habilitado(false);
    }
    
    private void habilitado(boolean flag) {
        campoNomeEdicao.setEnabled(flag);
        campoDataEdicao.setEnabled(flag);
        comboBoxIdosoEdicao.setEnabled(flag);
        listIdososEdicao.setEnabled(flag);
        botaoAdicionarEdicao.setEnabled(flag);
        botaoRemoverEdicao.setEnabled(flag);
        botaoSalvar.setEnabled(flag);
        comboFuncionarioConsulta.setEnabled(flag);
    }
    
    private void atualizaListaIdosos() {
        listIdosos.setListData(idosos.toArray());
    }
    
    private void atualizaListaIdososEdicao() {
        listIdososEdicao.setListData(idososEdicao.toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        botaoCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoData = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboBoxIdoso = new javax.swing.JComboBox();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIdosos = new javax.swing.JList();
        campoNome = new javax.swing.JTextField();
        comboFuncionario = new javax.swing.JComboBox();
        lFuncionario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comboBoxEvento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoDataEdicao = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        comboBoxIdosoEdicao = new javax.swing.JComboBox();
        botaoAdicionarEdicao = new javax.swing.JButton();
        botaoRemoverEdicao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listIdososEdicao = new javax.swing.JList();
        botaoSalvar = new javax.swing.JButton();
        campoNomeEdicao = new javax.swing.JTextField();
        botaoConsultar = new javax.swing.JButton();
        lFuncionarioConsulta = new javax.swing.JLabel();
        comboFuncionarioConsulta = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Evento");
        setResizable(false);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Data:");

        try {
            campoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Nome:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Idosos Participantes"));

        comboBoxIdoso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione idoso" }));

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listIdosos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxIdoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAdicionar))
                    .addComponent(botaoRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxIdoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRemover)
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        comboFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Funcionario" }));

        lFuncionario.setText("Funcionario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lFuncionario)
                            .addComponent(comboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(botaoCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel2);

        comboBoxEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione evento" }));

        jLabel3.setText("Nome:");

        jLabel5.setText("Data:");

        try {
            campoDataEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataEdicao.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Idosos Participantes"));

        comboBoxIdosoEdicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione idoso" }));
        comboBoxIdosoEdicao.setEnabled(false);

        botaoAdicionarEdicao.setText("Adicionar");
        botaoAdicionarEdicao.setEnabled(false);
        botaoAdicionarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarEdicaoActionPerformed(evt);
            }
        });

        botaoRemoverEdicao.setText("Remover");
        botaoRemoverEdicao.setEnabled(false);
        botaoRemoverEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverEdicaoActionPerformed(evt);
            }
        });

        listIdososEdicao.setEnabled(false);
        jScrollPane2.setViewportView(listIdososEdicao);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAdicionarEdicao)
                    .addComponent(botaoRemoverEdicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxIdosoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarEdicao)
                    .addComponent(comboBoxIdosoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRemoverEdicao)
                .addContainerGap())
        );

        botaoSalvar.setText("Salvar alterações");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        campoNomeEdicao.setEnabled(false);

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        lFuncionarioConsulta.setText("Funcionario:");

        comboFuncionarioConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Funcionario" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNomeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDataEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lFuncionarioConsulta)
                                    .addComponent(comboFuncionarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboBoxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoConsultar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(botaoSalvar)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNomeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFuncionarioConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoDataEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboFuncionarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        if(comboBoxIdoso.getSelectedIndex() != 0) {
            ListModel<Idoso> lista =  listIdosos.getModel();
            for(int i = 0; i < lista.getSize(); i++){
                Idoso idoso = lista.getElementAt(i);
                if(idoso.getNomeIdoso().equalsIgnoreCase(((Idoso)comboBoxIdoso.getSelectedItem()).getNomeIdoso())){
                    JOptionPane.showMessageDialog(null, "Idoso já está cadastrado no evento!");
                    return;
                }
            }
            idosos.add((Idoso) comboBoxIdoso.getSelectedItem());
            atualizaListaIdosos();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Idoso");
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        if(comboBoxIdoso.getSelectedIndex() != 0) {
            idosos.remove((Idoso) listIdosos.getSelectedValue());
            atualizaListaIdosos();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Idoso");
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        evento = new Evento();
        evento.setFunc((Funcionario)comboFuncionario.getSelectedItem());
        if(!campoNome.getText().equals("")) {
            evento.setNomeEvento(campoNome.getText());
        }
        else {
            Mensagens.campoInvalido(this, "Campo Nome");
            return;
        }
        if(ComponentValidator.date(campoData)) {
            evento.setDataEvento(campoData.getText());
        }
        else {
            Mensagens.campoInvalido(this, "Campo Data");
            return;
        }
        if(!idosos.isEmpty()) {
            evento.setListaIdosos(idosos);
        }
        else {
            Mensagens.campoInvalido(this, "Campo Lista de Idosos");
            return;
        }
        try {
            evento.setCodigo(ImplEventoDAO.getInstance().encontrarCodMax());
            ImplEventoDAO.getInstance().inserir(evento);
            limparCadastro();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        if(comboBoxEvento.getSelectedIndex() != 0) {
            habilitado(true);
            try {
                evento = (Evento) comboBoxEvento.getSelectedItem();
                campoNomeEdicao.setText(evento.getNomeEvento());
                campoDataEdicao.setText(evento.getDataEvento());
                
                ComboBoxModel<Funcionario> model =  comboFuncionarioConsulta.getModel();
                for(int i = 1; i < model.getSize();i++){
                    Funcionario f = model.getElementAt(i);
                    if(f.getCodFuncionario() == evento.getFunc().getCodFuncionario()){
                        comboFuncionarioConsulta.setSelectedIndex(i);
                    }
                }
                
                idososEdicao = new ArrayList<>();
                idososEdicao.addAll(evento.getListaIdosos());
                atualizaListaIdososEdicao();
            } catch(Exception ex) {
                ex.printStackTrace();
            }
            evento = (Evento) comboBoxEvento.getSelectedItem();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Evento");
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex() == 1) {
            try {
                comboBoxEvento.removeAllItems();
                comboBoxEvento.addItem("Selecione Evento");
                Date date = new Date();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY");
                String data = format.format(date);
                List<Evento> lista = ImplEventoDAO.getInstance().encontrarEventosAposData(data);
                if(lista != null) {
                    for (Iterator<Evento> it = lista.iterator(); it.hasNext();) {
                        Evento evento = it.next();
                        comboBoxEvento.addItem(evento);
                    }
                }
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(null, "Não existe evento disponível!");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void botaoRemoverEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverEdicaoActionPerformed
        if(comboBoxIdosoEdicao.getSelectedIndex() != 0) {
            idososEdicao.remove((Idoso) listIdososEdicao.getSelectedValue());
            atualizaListaIdosos();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Idoso");
        }
    }//GEN-LAST:event_botaoRemoverEdicaoActionPerformed

    private void botaoAdicionarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarEdicaoActionPerformed
        if(comboBoxIdoso.getSelectedIndex() != 0) {
            idosos.add((Idoso) comboBoxIdoso.getSelectedItem());
            atualizaListaIdosos();
        }
        else {
            Mensagens.campoInvalido(this, "Campo Idoso");
        }
    }//GEN-LAST:event_botaoAdicionarEdicaoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        evento.setFunc((Funcionario)comboFuncionarioConsulta.getSelectedItem());
        if(!campoNomeEdicao.getText().equals("")) {
            evento.setNomeEvento(campoNomeEdicao.getText());
        }
        else {
            Mensagens.campoInvalido(this, "Campo Nome");
            return;
        }
        if(ComponentValidator.date(campoDataEdicao)) {
            evento.setDataEvento(campoDataEdicao.getText());
        }
        else {
            Mensagens.campoInvalido(this, "Campo Data");
            return;
        }
        if(!idososEdicao.isEmpty()) {
            evento.setListaIdosos(idososEdicao);
        }
        else {
            Mensagens.campoInvalido(this, "Campo Lista de Idosos");
            return;
        }
        try {
            ImplEventoDAO.getInstance().atualizar(evento);
            limparEdicao();
            habilitado(false);
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAdicionarEdicao;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoRemoverEdicao;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JFormattedTextField campoDataEdicao;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeEdicao;
    private javax.swing.JComboBox comboBoxEvento;
    private javax.swing.JComboBox comboBoxIdoso;
    private javax.swing.JComboBox comboBoxIdosoEdicao;
    private javax.swing.JComboBox comboFuncionario;
    private javax.swing.JComboBox comboFuncionarioConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lFuncionario;
    private javax.swing.JLabel lFuncionarioConsulta;
    private javax.swing.JList listIdosos;
    private javax.swing.JList listIdososEdicao;
    // End of variables declaration//GEN-END:variables
}
